server:
  port: 8080

districtName: Q1

api:
  mapbox:
    token: pk.eyJ1IjoidHVkYW9ia3UiLCJhIjoiY2tvZmQ2dnNtMDZlNjJwcG53bmw2YXRhYSJ9.quj8ggmNSoE2iKuzCOtU-g
    domain:  api.mapbox.com
    pathOptimized: /optimized-trips/v1/mapbox/
    pathDirections: /directions/v5/mapbox/driving-traffic/
    scheme: https

dynamic-routing:
  threshold: 1000
  weightTime: 1000
